### ISSUE TITLE
导入错误

### ISSUE THREAD

**Issue by TomTom18-eng** [XiaoliChan/CrackMapExec-Extension#1]
您好，我这边在导入的时候收到以下错误，这是什么问题
  File "/usr/lib/python3/dist-packages/cme/crackmapexec.py", line 117, in main
    args = gen_cli_args()
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cme/cli.py", line 77, in gen_cli_args
    subparsers = getattr(protocol_object, protocol).proto_args(subparsers, std_parser, module_parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/cme/protocols/wmi.py", line 40, in proto_args
    no_smb_arg = wmi_parser.add_argument("--no-smb", action=get_conditional_action(_StoreTrueAction), make_required=[], help='No smb connection')
                                                            ^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'get_conditional_action' is not defined

**Comment by XiaoliChan** [comment]
您好，请问你解决了吗？
