### ISSUE TITLE
mpgn的CrackMapExec好像删掉了

### ISSUE THREAD

**Issue by yukar1z0e** [XiaoliChan/CrackMapExec-Extension#2]
mpgn的CrackMapExec好像删掉了，有谁fork了吗...
<img width="1359" alt="" src="https://github.com/XiaoliChan/CrackMapExec-Extension/assets/44317939/61049628-01d0-416f-8034-31948a6b6354">

**Comment by XiaoliChan** [comment]
已经在官方了，mpgn退出了CME项目，原来7k +star的也准备商业化了
- https://github.com/Porchetta-Industries/CrackMapExec

推荐你用这个，下面这个是fork的一个分支，并且打算持续化开源（未来要重新命名）
- https://github.com/Pennyw0rth/CrackMapExec

**Comment by XiaoliChan** [comment]
Closed
